### ISSUE TITLE
An error occurred when running the simulation: gneric_type: type "Hsync" is already registered

### ISSUE THREAD

**Issue by XieyangSun** [git-artes/gr-tempest#32]
Hi! I encountered an error when running "manual_simulated_tempest_example.grc":

```
Generating: "/home/sund/gr-tempest/examples/manual_simulated_tempest_example.py"

Executing: /usr/bin/python3 -u /home/sund/gr-tempest/examples/manual_simulated_tempest_example.py

Traceback (most recent call last):
  File "/home/sund/gr-tempest/examples/manual_simulated_tempest_example.py", line 30, in <module>
    import tempest
  File "/home/sund/prefix-3.10/lib/python3.10/site-packages/gnuradio/tempest/__init__.py", line 18, in <module>
    from .tempest_python import *
ImportError: generic_type: type "Hsync" is already registered!
free(): invalid pointer

&gt;&gt;&gt; Done (return code -6)
```

Before that, I also meet the problem:"ModuleNotFoundError: No module named 'tempest'" link: https://github.com/git-artes/gr-tempest/issues/10
Then I added PYTHONPATH "/home/sund/prefix-3.10/lib/python3.10/site-packages/gnuradio" (My GNURadio was installed via PYbombs). Now GNURadio can find the module 'tempest', but I meet the above problem.
Does anyone know how to solve this problem?

By the way,  I noticed that the users need to execute the 'FFT_autocorrelate.grc' and 'Keep_1_in_N_Frames.grc' in GNURadio before they start to use gr-tempest. Otherwise, these two key modules cannot be invoked in GNURadio.
But this solution is only mentioned in one issue. If anyone is running gr-tempest for the first time, you can try running the above two grc once~

**Comment by XieyangSun** [comment]
I found the reason for this mistake.  As mentioned by issue15 [https://github.com/git-artes/gr-tempest/issues/15], when running the 'manual_simulated_tempest_example.grc', the generated .py file repeatedly imports 'tempest'.
I removed 'import tempest' and ran 'python3 manual_simulated_tempest_example.py' at the command line and it work~

Although I did not locate the specific module that caused the repeated import (I guess modules 'Fine sampling synchronization' and 'Normalize Flow').
