### ISSUE TITLE
Starting problem semi_automatic_tempest_example

### ISSUE THREAD

**Issue by Ferditore** [git-artes/gr-tempest#9]
When running an example from the gr-tempest / examples library, I have the following problems finding the default list item. The program swears and gives an error. How to deal with this?
I have GNU Radio Companion v3.8.2.0-119-gcba012fb, UHD 4.0.0.0-133-g7ec04886 and Volk 2.0. on  a Virtual Machine Ubuntu 21.04 64-bit.

Below is the log from the GNU Radio terminal and the screen of the program

Generating: '/home/gnu/workarea/gr-tempest/examples/semi_automatic_tempest_example.py'
Executing: /usr/bin/python3 -u /home/gnu/workarea/gr-tempest/examples/semi_automatic_tempest_example.py
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Traceback (most recent call last):
  File "/home/gnu/workarea/gr-tempest/examples/semi_automatic_tempest_example.py", line 438, in <module>
    main()
  File "/home/gnu/workarea/gr-tempest/examples/semi_automatic_tempest_example.py", line 414, in main
    tb = top_block_cls()
  File "/home/gnu/workarea/gr-tempest/examples/semi_automatic_tempest_example.py", line 131, in __init__
    self._mode_callback(self.mode)
  File "/home/gnu/workarea/gr-tempest/examples/semi_automatic_tempest_example.py", line 130, in <lambda>
    self._mode_callback = lambda i: Qt.QMetaObject.invokeMethod(self._mode_combo_box, "setCurrentIndex", Qt.Q_ARG("int", self._mode_options.index(i)))
ValueError: 20 is not in list
>>> Done (return code 1)

![image](https://user-images.githubusercontent.com/71971552/120446787-95c09580-c392-11eb-8d66-058a5612d21a.png)

**Comment by bkerler** [comment]
Just replace "[x for x in range(len(modes))]" as option in the qt gui chooser
